# Generated by Django 6.0.1 on 2026-01-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_profit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
